version: "3"
services:
    zac-bot:
        build: .
        image: zac-bot:latest
        container_name: zac-bot
        hostname: zac-bot
        command: ash -c 'cd /zac-bot/ && python3 ./main.py'
        volumes:
            - ./:/zac-bot/
